name: Optimize Images
on:
  push:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
    branches:
      - main

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Optimize Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: '85'
          pngQuality: '85'
          ignorePaths: 'node_modules/**'
