name: Validate HTML and Links
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Всяка неделя

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
          format: text
          log_level: INFO

      - name: Check Links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress './**/*.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
